/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shoemanagementsystem;

import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author mnawa
 */
public class ColorSizeFrame extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement st;
    ResultSet rs;

    String color;

    int q40M = 1;
    int q41M = 1;
    int q42M = 1;
    int q43M = 1;
    int q44M = 1;
    int q45M = 1;
    int q46M = 1;

    int q36W = 1;
    int q37W = 1;
    int q38W = 1;
    int q39W = 1;
    int q40W = 1;
    int q41W = 1;
    int q42W = 1;

    public ColorSizeFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        blackM = new javax.swing.JCheckBox();
        brownM = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        size40M = new javax.swing.JCheckBox();
        size41M = new javax.swing.JCheckBox();
        size42M = new javax.swing.JCheckBox();
        size43M = new javax.swing.JCheckBox();
        size44M = new javax.swing.JCheckBox();
        size45M = new javax.swing.JCheckBox();
        size46M = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        brownW = new javax.swing.JCheckBox();
        blackW = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        qty40M = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        qty41M = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        qty42M = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        qty43M = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        qty45M = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        qty44M = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        qty46M = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        size39W = new javax.swing.JCheckBox();
        size41W = new javax.swing.JCheckBox();
        jSeparator8 = new javax.swing.JSeparator();
        qty36W = new javax.swing.JTextField();
        size38W = new javax.swing.JCheckBox();
        size36W = new javax.swing.JCheckBox();
        size42W = new javax.swing.JCheckBox();
        size37W = new javax.swing.JCheckBox();
        size40W = new javax.swing.JCheckBox();
        qty37W = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        qty38W = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        qty39W = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        qty41W = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        qty40W = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        qty42W = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        totalQty = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(10, 10, 10));
        jPanel6.setForeground(new java.awt.Color(51, 51, 51));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Add Colors and Sizes");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(286, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(251, 251, 251)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 60));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel7.setBackground(new java.awt.Color(18, 18, 18));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Colors (Men)");

        blackM.setBackground(new java.awt.Color(18, 18, 18));
        blackM.setForeground(new java.awt.Color(255, 255, 255));
        blackM.setText("Black");
        blackM.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                blackMItemStateChanged(evt);
            }
        });

        brownM.setBackground(new java.awt.Color(18, 18, 18));
        brownM.setForeground(new java.awt.Color(255, 255, 255));
        brownM.setText("Brown");
        brownM.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                brownMItemStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Men Shoe Sizes");

        size40M.setBackground(new java.awt.Color(18, 18, 18));
        size40M.setForeground(new java.awt.Color(255, 255, 255));
        size40M.setText("40");
        size40M.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                size40MItemStateChanged(evt);
            }
        });
        size40M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                size40MActionPerformed(evt);
            }
        });

        size41M.setBackground(new java.awt.Color(18, 18, 18));
        size41M.setForeground(new java.awt.Color(255, 255, 255));
        size41M.setText("41");
        size41M.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                size41MItemStateChanged(evt);
            }
        });
        size41M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                size41MActionPerformed(evt);
            }
        });

        size42M.setBackground(new java.awt.Color(18, 18, 18));
        size42M.setForeground(new java.awt.Color(255, 255, 255));
        size42M.setText("42");
        size42M.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                size42MItemStateChanged(evt);
            }
        });

        size43M.setBackground(new java.awt.Color(18, 18, 18));
        size43M.setForeground(new java.awt.Color(255, 255, 255));
        size43M.setText("43");
        size43M.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                size43MItemStateChanged(evt);
            }
        });

        size44M.setBackground(new java.awt.Color(18, 18, 18));
        size44M.setForeground(new java.awt.Color(255, 255, 255));
        size44M.setText("44");
        size44M.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                size44MItemStateChanged(evt);
            }
        });

        size45M.setBackground(new java.awt.Color(18, 18, 18));
        size45M.setForeground(new java.awt.Color(255, 255, 255));
        size45M.setText("45");
        size45M.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                size45MItemStateChanged(evt);
            }
        });

        size46M.setBackground(new java.awt.Color(18, 18, 18));
        size46M.setForeground(new java.awt.Color(255, 255, 255));
        size46M.setText("46");
        size46M.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                size46MItemStateChanged(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Women Shoe Sizes");

        brownW.setBackground(new java.awt.Color(18, 18, 18));
        brownW.setForeground(new java.awt.Color(255, 255, 255));
        brownW.setText("Brown");
        brownW.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                brownWItemStateChanged(evt);
            }
        });

        blackW.setBackground(new java.awt.Color(18, 18, 18));
        blackW.setForeground(new java.awt.Color(255, 255, 255));
        blackW.setText("Black");
        blackW.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                blackWItemStateChanged(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Colors (Women)");

        qty40M.setBackground(new java.awt.Color(18, 18, 18));
        qty40M.setForeground(new java.awt.Color(255, 255, 255));
        qty40M.setText("Quantity");
        qty40M.setBorder(null);
        qty40M.setCaretColor(new java.awt.Color(255, 255, 255));
        qty40M.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                qty40MFocusGained(evt);
            }
        });

        qty41M.setBackground(new java.awt.Color(18, 18, 18));
        qty41M.setForeground(new java.awt.Color(255, 255, 255));
        qty41M.setText("Quantity");
        qty41M.setBorder(null);
        qty41M.setCaretColor(new java.awt.Color(255, 255, 255));
        qty41M.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                qty41MFocusGained(evt);
            }
        });

        qty42M.setBackground(new java.awt.Color(18, 18, 18));
        qty42M.setForeground(new java.awt.Color(255, 255, 255));
        qty42M.setText("Quantity");
        qty42M.setBorder(null);
        qty42M.setCaretColor(new java.awt.Color(255, 255, 255));
        qty42M.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                qty42MFocusGained(evt);
            }
        });

        qty43M.setBackground(new java.awt.Color(18, 18, 18));
        qty43M.setForeground(new java.awt.Color(255, 255, 255));
        qty43M.setText("Quantity");
        qty43M.setBorder(null);
        qty43M.setCaretColor(new java.awt.Color(255, 255, 255));
        qty43M.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                qty43MFocusGained(evt);
            }
        });

        qty45M.setBackground(new java.awt.Color(18, 18, 18));
        qty45M.setForeground(new java.awt.Color(255, 255, 255));
        qty45M.setText("Quantity");
        qty45M.setBorder(null);
        qty45M.setCaretColor(new java.awt.Color(255, 255, 255));
        qty45M.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                qty45MFocusGained(evt);
            }
        });

        qty44M.setBackground(new java.awt.Color(18, 18, 18));
        qty44M.setForeground(new java.awt.Color(255, 255, 255));
        qty44M.setText("Quantity");
        qty44M.setBorder(null);
        qty44M.setCaretColor(new java.awt.Color(255, 255, 255));
        qty44M.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                qty44MFocusGained(evt);
            }
        });

        qty46M.setBackground(new java.awt.Color(18, 18, 18));
        qty46M.setForeground(new java.awt.Color(255, 255, 255));
        qty46M.setText("Quantity");
        qty46M.setBorder(null);
        qty46M.setCaretColor(new java.awt.Color(255, 255, 255));
        qty46M.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                qty46MFocusGained(evt);
            }
        });

        size39W.setBackground(new java.awt.Color(18, 18, 18));
        size39W.setForeground(new java.awt.Color(255, 255, 255));
        size39W.setText("39");
        size39W.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                size39WItemStateChanged(evt);
            }
        });

        size41W.setBackground(new java.awt.Color(18, 18, 18));
        size41W.setForeground(new java.awt.Color(255, 255, 255));
        size41W.setText("41");
        size41W.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                size41WItemStateChanged(evt);
            }
        });

        qty36W.setBackground(new java.awt.Color(18, 18, 18));
        qty36W.setForeground(new java.awt.Color(255, 255, 255));
        qty36W.setText("Quantity");
        qty36W.setBorder(null);
        qty36W.setCaretColor(new java.awt.Color(255, 255, 255));
        qty36W.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                qty36WFocusGained(evt);
            }
        });

        size38W.setBackground(new java.awt.Color(18, 18, 18));
        size38W.setForeground(new java.awt.Color(255, 255, 255));
        size38W.setText("38");
        size38W.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                size38WItemStateChanged(evt);
            }
        });

        size36W.setBackground(new java.awt.Color(18, 18, 18));
        size36W.setForeground(new java.awt.Color(255, 255, 255));
        size36W.setText("36");
        size36W.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                size36WItemStateChanged(evt);
            }
        });
        size36W.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                size36WActionPerformed(evt);
            }
        });

        size42W.setBackground(new java.awt.Color(18, 18, 18));
        size42W.setForeground(new java.awt.Color(255, 255, 255));
        size42W.setText("42");
        size42W.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                size42WItemStateChanged(evt);
            }
        });

        size37W.setBackground(new java.awt.Color(18, 18, 18));
        size37W.setForeground(new java.awt.Color(255, 255, 255));
        size37W.setText("37");
        size37W.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                size37WItemStateChanged(evt);
            }
        });
        size37W.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                size37WActionPerformed(evt);
            }
        });

        size40W.setBackground(new java.awt.Color(18, 18, 18));
        size40W.setForeground(new java.awt.Color(255, 255, 255));
        size40W.setText("40");
        size40W.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                size40WItemStateChanged(evt);
            }
        });

        qty37W.setBackground(new java.awt.Color(18, 18, 18));
        qty37W.setForeground(new java.awt.Color(255, 255, 255));
        qty37W.setText("Quantity");
        qty37W.setBorder(null);
        qty37W.setCaretColor(new java.awt.Color(255, 255, 255));
        qty37W.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                qty37WFocusGained(evt);
            }
        });

        qty38W.setBackground(new java.awt.Color(18, 18, 18));
        qty38W.setForeground(new java.awt.Color(255, 255, 255));
        qty38W.setText("Quantity");
        qty38W.setBorder(null);
        qty38W.setCaretColor(new java.awt.Color(255, 255, 255));
        qty38W.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                qty38WFocusGained(evt);
            }
        });

        qty39W.setBackground(new java.awt.Color(18, 18, 18));
        qty39W.setForeground(new java.awt.Color(255, 255, 255));
        qty39W.setText("Quantity");
        qty39W.setBorder(null);
        qty39W.setCaretColor(new java.awt.Color(255, 255, 255));
        qty39W.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                qty39WFocusGained(evt);
            }
        });

        qty41W.setBackground(new java.awt.Color(18, 18, 18));
        qty41W.setForeground(new java.awt.Color(255, 255, 255));
        qty41W.setText("Quantity");
        qty41W.setBorder(null);
        qty41W.setCaretColor(new java.awt.Color(255, 255, 255));
        qty41W.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                qty41WFocusGained(evt);
            }
        });

        qty40W.setBackground(new java.awt.Color(18, 18, 18));
        qty40W.setForeground(new java.awt.Color(255, 255, 255));
        qty40W.setText("Quantity");
        qty40W.setBorder(null);
        qty40W.setCaretColor(new java.awt.Color(255, 255, 255));
        qty40W.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                qty40WFocusGained(evt);
            }
        });

        qty42W.setBackground(new java.awt.Color(18, 18, 18));
        qty42W.setForeground(new java.awt.Color(255, 255, 255));
        qty42W.setText("Quantity");
        qty42W.setBorder(null);
        qty42W.setCaretColor(new java.awt.Color(255, 255, 255));
        qty42W.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                qty42WFocusGained(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(187, 134, 252));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Total QTY");

        totalQty.setEditable(false);
        totalQty.setBackground(new java.awt.Color(18, 18, 18));
        totalQty.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        totalQty.setForeground(new java.awt.Color(255, 255, 255));
        totalQty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalQty.setBorder(null);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(blackM)
                            .addComponent(jLabel7)
                            .addComponent(brownM)
                            .addComponent(jLabel8)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(size43M)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator4)
                                    .addComponent(qty43M, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(size44M)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator5)
                                    .addComponent(qty44M, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(size40M)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(qty40M, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(size42M)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator3)
                                    .addComponent(qty42M, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(size46M)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator7)
                                    .addComponent(qty46M, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)))
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(size45M)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(qty45M, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                    .addComponent(size41M)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator2)
                                        .addComponent(qty41M, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)))))
                        .addGap(118, 118, 118)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(brownW)
                            .addComponent(blackW)
                            .addComponent(jLabel10)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(size39W)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator11)
                                        .addComponent(qty39W, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)))
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(size40W)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator12)
                                        .addComponent(qty40W)))
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(size36W)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator8)
                                        .addComponent(qty36W)))
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(size37W)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator9)
                                        .addComponent(qty37W)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                    .addComponent(size38W)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator10)
                                        .addComponent(qty38W, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))))
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                    .addComponent(size42W)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(qty42W, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                    .addComponent(size41W)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(qty41W))
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGap(43, 43, 43)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator13, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                                        .addComponent(jSeparator14))))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator15)
                            .addComponent(totalQty, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(blackM)
                        .addGap(18, 18, 18)
                        .addComponent(brownM)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel8))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(blackW)
                        .addGap(18, 18, 18)
                        .addComponent(brownW)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel9)))
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(size40M)
                            .addComponent(qty40M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(size41M)
                            .addComponent(qty41M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(size42M)
                            .addComponent(qty42M))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(size43M)
                            .addComponent(qty43M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(size44M)
                            .addComponent(qty44M))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(size45M)
                            .addComponent(qty45M))
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(size46M)
                            .addComponent(qty46M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(size36W)
                                    .addComponent(qty36W, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(size37W)
                                    .addComponent(qty37W, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(size38W)
                                    .addComponent(qty38W))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(size39W)
                                    .addComponent(qty39W, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(size40W)
                                    .addComponent(qty40W, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(size41W)
                                    .addComponent(qty41W))
                                .addGap(1, 1, 1)
                                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(size42W)
                                    .addComponent(qty42W, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)
                                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(totalQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(37, 37, 37))))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 750, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    void getQTY()
    {
     qty40M.getDocument().addDocumentListener(new DocumentListener() {
         @Override
         public void insertUpdate(DocumentEvent e) {
            
         }

         @Override
         public void removeUpdate(DocumentEvent e) {
             throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
         }

         @Override
         public void changedUpdate(DocumentEvent e) {
             throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
         }
     });
     qty41M.getDocument().addDocumentListener(new DocumentListener() {
         @Override
         public void insertUpdate(DocumentEvent e) {
             throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
         }

         @Override
         public void removeUpdate(DocumentEvent e) {
             throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
         }

         @Override
         public void changedUpdate(DocumentEvent e) {
             throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
         }
     });
     qty42M.getDocument().addDocumentListener(new DocumentListener() {
         @Override
         public void insertUpdate(DocumentEvent e) {
             throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
         }

         @Override
         public void removeUpdate(DocumentEvent e) {
             throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
         }

         @Override
         public void changedUpdate(DocumentEvent e) {
             throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
         }
     });
     qty43M.getDocument().addDocumentListener(new DocumentListener() {
         @Override
         public void insertUpdate(DocumentEvent e) {
             throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
         }

         @Override
         public void removeUpdate(DocumentEvent e) {
             throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
         }

         @Override
         public void changedUpdate(DocumentEvent e) {
             throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
         }
     });
     qty44M.getDocument().addDocumentListener(new DocumentListener() {
         @Override
         public void insertUpdate(DocumentEvent e) {
             throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
         }

         @Override
         public void removeUpdate(DocumentEvent e) {
             throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
         }

         @Override
         public void changedUpdate(DocumentEvent e) {
             throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
         }
     });
     qty45M.getDocument().addDocumentListener(new DocumentListener() {
         @Override
         public void insertUpdate(DocumentEvent e) {
             throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
         }

         @Override
         public void removeUpdate(DocumentEvent e) {
             throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
         }

         @Override
         public void changedUpdate(DocumentEvent e) {
             throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
         }
     });
     qty46M.getDocument().addDocumentListener(new DocumentListener() {
         @Override
         public void insertUpdate(DocumentEvent e) {
             throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
         }

         @Override
         public void removeUpdate(DocumentEvent e) {
             throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
         }

         @Override
         public void changedUpdate(DocumentEvent e) {
             throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
         }
     });
        
    }
    
    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void size40MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_size40MActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_size40MActionPerformed

    private void size41MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_size41MActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_size41MActionPerformed

    private void qty40MFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qty40MFocusGained
        qty40M.setText("");
    }//GEN-LAST:event_qty40MFocusGained

    private void qty41MFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qty41MFocusGained
        qty41M.setText("");

    }//GEN-LAST:event_qty41MFocusGained

    private void qty42MFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qty42MFocusGained
        qty42M.setText("");

    }//GEN-LAST:event_qty42MFocusGained

    private void qty43MFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qty43MFocusGained
        qty43M.setText("");

    }//GEN-LAST:event_qty43MFocusGained

    private void qty44MFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qty44MFocusGained
        qty44M.setText("");

    }//GEN-LAST:event_qty44MFocusGained

    private void qty45MFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qty45MFocusGained
        qty45M.setText("");

    }//GEN-LAST:event_qty45MFocusGained

    private void qty46MFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qty46MFocusGained
        qty46M.setText("");

    }//GEN-LAST:event_qty46MFocusGained

    private void qty36WFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qty36WFocusGained
        qty36W.setText("");
    }//GEN-LAST:event_qty36WFocusGained

    private void size36WActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_size36WActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_size36WActionPerformed

    private void size37WActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_size37WActionPerformed


    }//GEN-LAST:event_size37WActionPerformed

    private void qty37WFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qty37WFocusGained
        qty37W.setText("");
    }//GEN-LAST:event_qty37WFocusGained

    private void qty38WFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qty38WFocusGained
        qty38W.setText("");
    }//GEN-LAST:event_qty38WFocusGained

    private void qty39WFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qty39WFocusGained
        qty39W.setText("");
    }//GEN-LAST:event_qty39WFocusGained

    private void qty41WFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qty41WFocusGained
        qty41W.setText("");
    }//GEN-LAST:event_qty41WFocusGained

    private void qty40WFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qty40WFocusGained
        qty40W.setText("");
    }//GEN-LAST:event_qty40WFocusGained

    private void qty42WFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qty42WFocusGained
        qty42W.setText("");
    }//GEN-LAST:event_qty42WFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AddProduct();


    }//GEN-LAST:event_jButton1ActionPerformed

    void AddProduct() {
        conn = DBConnection.getConnection();

        if ((q40M == 0 || q41M == 0 || q42M == 0 || q43M == 0 || q44M == 0 || q45M == 0 || q46M == 0 || q36W == 0 || q37W == 0 || q38W == 0 || q39W == 0 || q40W == 0 || q41W == 0 || q42W == 0)) {
            if (men) {

                try {

                    q40M = Integer.valueOf(qty40M.getText());
                } catch (Exception e) {

                    q40M = 0;
                }
                try {
                    q41M = Integer.valueOf(qty41M.getText());
                } catch (Exception e) {

                    q41M = 0;
                }
                try {

                    q42M = Integer.valueOf(qty42M.getText());
                } catch (Exception e) {

                    q42M = 0;
                }
                try {

                    q43M = Integer.valueOf(qty43M.getText());
                } catch (Exception e) {

                    q43M = 0;
                }
                try {

                    q44M = Integer.valueOf(qty44M.getText());
                } catch (Exception e) {

                    q44M = 0;
                }
                try {

                    q45M = Integer.valueOf(qty45M.getText());
                } catch (Exception e) {

                    q45M = 0;
                }
                try {

                    q46M = Integer.valueOf(qty46M.getText());
                } catch (Exception e) {

                    q46M = 0;
                }

                try {
                    getMaleID();
                    st = conn.prepareStatement("insert into colorsizemen values(?,?,?,?,?,?,?,?,?,?)");
                    st.setInt(1, id);
                    st.setString(2, userdetails.code);
                    st.setString(3, color);
                    st.setInt(4, q40M);
                    st.setInt(5, q41M);
                    st.setInt(6, q42M);
                    st.setInt(7, q43M);
                    st.setInt(8, q44M);
                    st.setInt(9, q45M);
                    st.setInt(10, q46M);
                    st.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Selected Color and Sizes are added", "Success", JOptionPane.INFORMATION_MESSAGE);

                    if (JOptionPane.showConfirmDialog(null, "Do you want to add more color and size for this item?", "Question", JOptionPane.YES_NO_OPTION) == 0) {
                        if (men) {
                            setMen();

                        } else if (women) {
                            setWomen();

                        }

                    } else {
                        this.dispose();

                    }
                } catch (SQLException ex) {
                    Logger.getLogger(ColorSizeFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (women) {

                try {

                    q36W = Integer.valueOf(qty36W.getText());
                } catch (Exception e) {

                    q36W = 0;
                }
                try {
                    q37W = Integer.valueOf(qty37W.getText());
                } catch (Exception e) {

                    q37W = 0;
                }
                try {

                    q38W = Integer.valueOf(qty38W.getText());
                } catch (Exception e) {

                    q38W = 0;
                }
                try {

                    q39W = Integer.valueOf(qty39W.getText());
                } catch (Exception e) {

                    q39W = 0;
                }
                try {

                    q40W = Integer.valueOf(qty40W.getText());
                } catch (Exception e) {

                    q40W = 0;
                }
                try {

                    q41W = Integer.valueOf(qty41M.getText());
                } catch (Exception e) {

                    q41W = 0;
                }
                try {

                    q42W = Integer.valueOf(qty42W.getText());
                } catch (Exception e) {

                    q42W = 0;
                }

                

                try {
                    getFemaleID();
                    st = conn.prepareStatement("insert into colorsizewomen values(?,?,?,?,?,?,?,?,?,?)");
                    st.setInt(1, id);
                    st.setString(2, userdetails.code);
                    st.setString(3, color);
                    st.setInt(4, q36W);
                    st.setInt(5, q37W);
                    st.setInt(6, q38W);
                    st.setInt(7, q39W);
                    st.setInt(8, q40W);
                    st.setInt(9, q41W);
                    st.setInt(10, q42W);

                    st.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Selected Color and Sizes are added", "Success", JOptionPane.INFORMATION_MESSAGE);

                    if (JOptionPane.showConfirmDialog(null, "Do you want to add more color and size for this item?", "Question", JOptionPane.YES_NO_OPTION) == 0) {
                        if (men) {
                            setMen();

                        } else if (women) {
                            setWomen();

                        }

                    } else {
                        this.dispose();

                    }
                } catch (SQLException ex) {
                    Logger.getLogger(ColorSizeFrame.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        } else {
            JOptionPane.showMessageDialog(null, "Please insert quantity for selected sizes", "Error", JOptionPane.ERROR_MESSAGE);

        }

    }

    int id;

    void getMaleID() {
        try {
            conn = DBConnection.getConnection();
            st = conn.prepareStatement("select max(id) from colorsizemen");
            rs = st.executeQuery();
            if (rs.next()) {
                id = rs.getInt(1) + 1;
            }
        } catch (SQLException ex) {
            Logger.getLogger(ColorSizeFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    void getFemaleID() {
        try {
            conn = DBConnection.getConnection();
            st = conn.prepareStatement("select max(id) from colorsizewomen");
            rs = st.executeQuery();
            if (rs.next()) {
                id = rs.getInt(1) + 1;
            }
        } catch (SQLException ex) {
            Logger.getLogger(ColorSizeFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void blackMItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_blackMItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            color = "Black";
            brownM.setSelected(false);
        }
    }//GEN-LAST:event_blackMItemStateChanged

    private void brownMItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_brownMItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            color = "Brown";

            blackM.setSelected(false);
        }
    }//GEN-LAST:event_brownMItemStateChanged

    private void blackWItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_blackWItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            color = "Black";

            brownW.setSelected(false);
        }
    }//GEN-LAST:event_blackWItemStateChanged

    private void brownWItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_brownWItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            color = "Brown";

            blackW.setSelected(false);
        }
    }//GEN-LAST:event_brownWItemStateChanged

    private void size40MItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_size40MItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            qty40M.setEnabled(true);
            q40M = 0;
        } else {
            qty40M.setEnabled(false);
            q40M = -1;
        }
    }//GEN-LAST:event_size40MItemStateChanged

    private void size41MItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_size41MItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            qty41M.setEnabled(true);
            q41M = 0;

        } else {
            qty41M.setEnabled(false);
            q41M = -1;

        }
    }//GEN-LAST:event_size41MItemStateChanged

    private void size42MItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_size42MItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            qty42M.setEnabled(true);
            q42M = 0;

        } else {
            qty42M.setEnabled(false);
            q42M = -1;

        }
    }//GEN-LAST:event_size42MItemStateChanged

    private void size43MItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_size43MItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            qty43M.setEnabled(true);
            q43M = 0;

        } else {
            qty43M.setEnabled(false);
            q43M = -1;

        }
    }//GEN-LAST:event_size43MItemStateChanged

    private void size44MItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_size44MItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            qty44M.setEnabled(true);
            q44M = 0;

        } else {
            qty44M.setEnabled(false);
            q44M = -1;

        }
    }//GEN-LAST:event_size44MItemStateChanged

    private void size45MItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_size45MItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            qty45M.setEnabled(true);
            q45M = 0;

        } else {
            qty45M.setEnabled(false);
            q45M = -1;

        }
    }//GEN-LAST:event_size45MItemStateChanged

    private void size46MItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_size46MItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            qty46M.setEnabled(true);
            q46M = 0;

        } else {
            qty46M.setEnabled(false);
            q46M = -1;

        }
    }//GEN-LAST:event_size46MItemStateChanged

    private void size36WItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_size36WItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            qty36W.setEnabled(true);
            q36W = 0;

        } else {
            qty36W.setEnabled(false);
            q36W = -1;

        }
    }//GEN-LAST:event_size36WItemStateChanged

    private void size37WItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_size37WItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            qty37W.setEnabled(true);
            q37W = 0;

        } else {
            qty37W.setEnabled(false);
            q37W = -1;

        }
    }//GEN-LAST:event_size37WItemStateChanged

    private void size38WItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_size38WItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            qty38W.setEnabled(true);
            q38W = 0;

        } else {
            qty38W.setEnabled(false);
            q38W = -1;

        }
    }//GEN-LAST:event_size38WItemStateChanged

    private void size39WItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_size39WItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            qty39W.setEnabled(true);
            q39W = 0;

        } else {
            qty39W.setEnabled(false);
            q39W = -1;

        }
    }//GEN-LAST:event_size39WItemStateChanged

    private void size40WItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_size40WItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            qty40W.setEnabled(true);
            q40W = 0;

        } else {
            qty40W.setEnabled(false);
            q40W = -1;

        }
    }//GEN-LAST:event_size40WItemStateChanged

    private void size41WItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_size41WItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            qty41W.setEnabled(true);
            q41W = 0;

        } else {
            qty41W.setEnabled(false);
            q41W = -1;

        }
    }//GEN-LAST:event_size41WItemStateChanged

    private void size42WItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_size42WItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            qty42W.setEnabled(true);
            q42W = 0;

        } else {
            qty42W.setEnabled(false);
            q42W = -1;

        }
    }//GEN-LAST:event_size42WItemStateChanged

    void disableAll() {
        qty40M.setEnabled(false);
        qty41M.setEnabled(false);
        qty42M.setEnabled(false);
        qty43M.setEnabled(false);
        qty44M.setEnabled(false);
        qty45M.setEnabled(false);
        qty46M.setEnabled(false);

        qty36W.setEnabled(false);
        qty37W.setEnabled(false);
        qty38W.setEnabled(false);
        qty39W.setEnabled(false);
        qty40W.setEnabled(false);
        qty41W.setEnabled(false);
        qty42W.setEnabled(false);

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColorSizeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColorSizeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColorSizeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColorSizeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        new ColorSizeFrame().setVisible(true);
    }

    static boolean men = false;
    static boolean women = false;

    public void setMen() {

        men = true;
        // colors
        blackM.setEnabled(true);
        brownM.setEnabled(true);

        /// sizes 
        size40M.setEnabled(true);
        size41M.setEnabled(true);
        size42M.setEnabled(true);
        size43M.setEnabled(true);
        size44M.setEnabled(true);
        size45M.setEnabled(true);
        size46M.setEnabled(true);

        qty40M.setEnabled(true);
        qty41M.setEnabled(true);
        qty42M.setEnabled(true);
        qty43M.setEnabled(true);
        qty44M.setEnabled(true);
        qty45M.setEnabled(true);
        qty46M.setEnabled(true);

        disableWomen();
    }

    void disableMen() {
        men = false;
        // colors
        blackM.setEnabled(false);
        brownM.setEnabled(false);

        /// sizes 
        size40M.setEnabled(false);
        size41M.setEnabled(false);
        size42M.setEnabled(false);
        size43M.setEnabled(false);
        size44M.setEnabled(false);
        size45M.setEnabled(false);
        size46M.setEnabled(false);

        qty40M.setEnabled(false);
        qty41M.setEnabled(false);
        qty42M.setEnabled(false);
        qty43M.setEnabled(false);
        qty44M.setEnabled(false);
        qty45M.setEnabled(false);
        qty46M.setEnabled(false);
    }

    void setWomen() {
        women = true;
        // colors
        blackW.setEnabled(true);
        brownW.setEnabled(true);

        /// sizes 
        size36W.setEnabled(true);
        size37W.setEnabled(true);
        size38W.setEnabled(true);
        size39W.setEnabled(true);
        size40W.setEnabled(true);
        size41W.setEnabled(true);
        size42W.setEnabled(true);

        qty36W.setEnabled(true);
        qty37W.setEnabled(true);
        qty38W.setEnabled(true);
        qty39W.setEnabled(true);
        qty40W.setEnabled(true);
        qty41W.setEnabled(true);
        qty42W.setEnabled(true);

        disableMen();

    }

    void disableWomen() {
        women = false;
        // colors
        blackW.setEnabled(false);
        brownW.setEnabled(false);

        /// sizes 
        size36W.setEnabled(false);
        size37W.setEnabled(false);
        size38W.setEnabled(false);
        size39W.setEnabled(false);
        size40W.setEnabled(false);
        size41W.setEnabled(false);
        size42W.setEnabled(false);

        qty36W.setEnabled(false);
        qty37W.setEnabled(false);
        qty38W.setEnabled(false);
        qty39W.setEnabled(false);
        qty40W.setEnabled(false);
        qty41W.setEnabled(false);
        qty42W.setEnabled(false);
    }

    public boolean getCategory() {
        if (men) {
            return men;
        } else {
            return women;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox blackM;
    private javax.swing.JCheckBox blackW;
    private javax.swing.JCheckBox brownM;
    private javax.swing.JCheckBox brownW;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField qty36W;
    private javax.swing.JTextField qty37W;
    private javax.swing.JTextField qty38W;
    private javax.swing.JTextField qty39W;
    private javax.swing.JTextField qty40M;
    private javax.swing.JTextField qty40W;
    private javax.swing.JTextField qty41M;
    private javax.swing.JTextField qty41W;
    private javax.swing.JTextField qty42M;
    private javax.swing.JTextField qty42W;
    private javax.swing.JTextField qty43M;
    private javax.swing.JTextField qty44M;
    private javax.swing.JTextField qty45M;
    private javax.swing.JTextField qty46M;
    private javax.swing.JCheckBox size36W;
    private javax.swing.JCheckBox size37W;
    private javax.swing.JCheckBox size38W;
    private javax.swing.JCheckBox size39W;
    private javax.swing.JCheckBox size40M;
    private javax.swing.JCheckBox size40W;
    private javax.swing.JCheckBox size41M;
    private javax.swing.JCheckBox size41W;
    private javax.swing.JCheckBox size42M;
    private javax.swing.JCheckBox size42W;
    private javax.swing.JCheckBox size43M;
    private javax.swing.JCheckBox size44M;
    private javax.swing.JCheckBox size45M;
    private javax.swing.JCheckBox size46M;
    private javax.swing.JTextField totalQty;
    // End of variables declaration//GEN-END:variables
}
