/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shoemanagementsystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author mnawa
 */
public class forgetPass extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement st = null;
    ResultSet rs = null;

    int xMouse;
    int yMouse;
    /**
     * Creates new form forgetPass
     */
    public forgetPass() {
        initComponents();
        disableComponents();
    }

    void disableComponents() {
        codeLbl.setEnabled(false);
        codeTF.setEnabled(false);
        verifyBtn.setEnabled(false);

        passwordPanel.setEnabled(false);

        newPassLbl.setEnabled(false);
        newPassTf.setEnabled(false);

        confirmPassLbl.setEnabled(false);
        confirmPassTf.setEnabled(false);

        doneBtn.setEnabled(false);
    }

    void enableComponents() {

        passwordPanel.setEnabled(true);

        newPassLbl.setEnabled(true);
        newPassTf.setEnabled(true);

        confirmPassLbl.setEnabled(true);
        confirmPassTf.setEnabled(true);

        doneBtn.setEnabled(true);

    }

    public void getEmail(int id) {
        try {

            conn = DBConnection.getConnection();
            st = conn.prepareStatement("select o_email from owner_signup where id=?");
            st.setInt(1, id);

            rs = st.executeQuery();
            if (rs.next()) {
                emailTF.setText(rs.getString("o_email"));
            }

        } catch (SQLException ex) {
            Logger.getLogger(forgetPass.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this number. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        emailPanel = new javax.swing.JPanel();
        codeTF = new javax.swing.JTextField();
        sendBtn = new javax.swing.JButton();
        codeLbl = new javax.swing.JLabel();
        mailLbl = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        verifyBtn = new javax.swing.JButton();
        passwordPanel = new javax.swing.JPanel();
        newPassTf = new javax.swing.JTextField();
        newPassLbl = new javax.swing.JLabel();
        doneBtn = new javax.swing.JButton();
        confirmPassLbl = new javax.swing.JLabel();
        confirmPassTf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reset Password");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("X");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        emailPanel.setBackground(new java.awt.Color(51, 51, 51));
        emailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email Verification", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.white));
        emailPanel.setForeground(new java.awt.Color(255, 255, 255));

        codeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeTFActionPerformed(evt);
            }
        });

        sendBtn.setBackground(new java.awt.Color(255, 255, 255));
        sendBtn.setText("Send code");
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });

        codeLbl.setBackground(new java.awt.Color(255, 255, 255));
        codeLbl.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        codeLbl.setForeground(new java.awt.Color(255, 255, 255));
        codeLbl.setText("Enter received code");

        mailLbl.setBackground(new java.awt.Color(255, 255, 255));
        mailLbl.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        mailLbl.setForeground(new java.awt.Color(255, 255, 255));
        mailLbl.setText("Enter your email");

        emailTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTFActionPerformed(evt);
            }
        });

        verifyBtn.setBackground(new java.awt.Color(102, 102, 255));
        verifyBtn.setText("Verify code");
        verifyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout emailPanelLayout = new javax.swing.GroupLayout(emailPanel);
        emailPanel.setLayout(emailPanelLayout);
        emailPanelLayout.setHorizontalGroup(
            emailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(emailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(emailPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(emailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(verifyBtn)
                        .addGroup(emailPanelLayout.createSequentialGroup()
                            .addGroup(emailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(mailLbl)
                                .addComponent(codeLbl))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(emailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(sendBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(emailTF, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(codeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(140, Short.MAX_VALUE)))
        );
        emailPanelLayout.setVerticalGroup(
            emailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
            .addGroup(emailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(emailPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(emailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(emailPanelLayout.createSequentialGroup()
                            .addGroup(emailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(mailLbl)
                                .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(sendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(33, 33, 33)
                            .addComponent(codeLbl))
                        .addComponent(codeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(verifyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        passwordPanel.setBackground(new java.awt.Color(51, 51, 51));
        passwordPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password Verification", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.white));
        passwordPanel.setForeground(new java.awt.Color(255, 255, 255));
        passwordPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newPassTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPassTfActionPerformed(evt);
            }
        });
        passwordPanel.add(newPassTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 169, 32));

        newPassLbl.setBackground(new java.awt.Color(255, 255, 255));
        newPassLbl.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        newPassLbl.setForeground(new java.awt.Color(255, 255, 255));
        newPassLbl.setText("Enter new password");
        passwordPanel.add(newPassLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        doneBtn.setBackground(new java.awt.Color(102, 102, 255));
        doneBtn.setText("Done");
        doneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneBtnActionPerformed(evt);
            }
        });
        passwordPanel.add(doneBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, 32));

        confirmPassLbl.setBackground(new java.awt.Color(255, 255, 255));
        confirmPassLbl.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        confirmPassLbl.setForeground(new java.awt.Color(255, 255, 255));
        confirmPassLbl.setText("Confirm new password");
        passwordPanel.add(confirmPassLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        confirmPassTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPassTfActionPerformed(evt);
            }
        });
        passwordPanel.add(confirmPassTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 169, 32));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(emailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void emailTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTFActionPerformed
        // TODO add your handling number here:
    }//GEN-LAST:event_emailTFActionPerformed

    private void codeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeTFActionPerformed
        // TODO add your handling number here:
    }//GEN-LAST:event_codeTFActionPerformed

    private void verifyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyBtnActionPerformed
        // TODO add your handling number here:
        if (codeTF.getText().equals(code)) {
            JOptionPane.showMessageDialog(this, "Code matched");
            codeLbl.setEnabled(false);
            codeTF.setEnabled(false);
            verifyBtn.setEnabled(false);
            enableComponents();
        }
    }//GEN-LAST:event_verifyBtnActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling number here:
        this.dispose();
        new LoginPage().setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked
    Random random;
    String code;
    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        // TODO add your handling number here:
        if (emailTF.getText().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Please enter email..", "Email not inserted", JOptionPane.ERROR_MESSAGE);
        } else if (!emailTF.getText().contains("@gmail.com")) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email example: abc@gmail.com", "Invalid Email", JOptionPane.ERROR_MESSAGE);
        } else {
            mailLbl.setEnabled(false);
            emailTF.setEnabled(false);
            sendBtn.setEnabled(false);

            codeLbl.setEnabled(true);
            codeTF.setEnabled(true);
            verifyBtn.setEnabled(true);

            random = new Random();
            int number = random.nextInt(999999);
            code = String.format("%06d", number);
            System.out.println(code);
            // Recipient's email ID needs to be mentioned.
            String to = emailTF.getText();

            // Sender's email ID needs to be mentioned
            String from = "syyedmnawazshah@gmail.com";

            // Assuming you are sending email from through gmails smtp
            String host = "smtp.gmail.com";

            // Get system properties
            Properties properties = System.getProperties();

            // Setup mail server
            properties.put("mail.smtp.host", host);
            properties.put("mail.smtp.port", "465");
            properties.put("mail.smtp.ssl.enable", "true");
            properties.put("mail.smtp.auth", "true");

            // Get the Session object.// and pass username and password
            Session session = Session.getInstance(properties, new javax.mail.Authenticator() {

                protected PasswordAuthentication getPasswordAuthentication() {

                    return new PasswordAuthentication("syyedmnawazshah@gmail.com", "ilovepakistan");

                }

            });

            // Used to debug SMTP issues
            session.setDebug(true);

            try {
                // Create a default MimeMessage object.
                MimeMessage message = new MimeMessage(session);

                // Set From: header field of the header.
                message.setFrom(new InternetAddress(from));

                // Set To: header field of the header.
                message.addRecipient(Message.RecipientType.TO, new InternetAddress(to));

                // Set Subject: header field
                message.setSubject("Verification");

                // Now set the actual message
                message.setText("Your reset password verification code is " + code);
                JOptionPane.showMessageDialog(this, "sending verification code ...", "Sending", JOptionPane.PLAIN_MESSAGE);

                // Send message
                Transport.send(message);
                JOptionPane.showMessageDialog(this, "Code sent successfully ...", "Sent", JOptionPane.PLAIN_MESSAGE);

            } catch (MessagingException mex) {
                mex.printStackTrace();
            }
        }
    }//GEN-LAST:event_sendBtnActionPerformed

    private void newPassTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPassTfActionPerformed
        // TODO add your handling number here:
    }//GEN-LAST:event_newPassTfActionPerformed

    private void doneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneBtnActionPerformed

        if (newPassTf.getText().equals(confirmPassTf.getText())) {

            try {
           String sql="update owner_signup set o_password='" + confirmPassTf.getText() + "' where o_email='" + emailTF.getText() + "'";
                Statement st = conn.createStatement();
                st.executeUpdate(sql);

                JOptionPane.showMessageDialog(this, "Passwords Changed Successfuly", "success", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                new LoginPage().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(forgetPass.class.getName()).log(Level.SEVERE, null, ex);

            }
        } else {
            JOptionPane.showMessageDialog(this, "Passwords not matched", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_doneBtnActionPerformed

    private void confirmPassTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPassTfActionPerformed
        // TODO add your handling number here:
    }//GEN-LAST:event_confirmPassTfActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
         int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
       xMouse=evt.getX();
       yMouse=evt.getY();
    }//GEN-LAST:event_formMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting number (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Darcula".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgetPass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codeLbl;
    private javax.swing.JTextField codeTF;
    private javax.swing.JLabel confirmPassLbl;
    private javax.swing.JTextField confirmPassTf;
    private javax.swing.JButton doneBtn;
    private javax.swing.JPanel emailPanel;
    private javax.swing.JTextField emailTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mailLbl;
    private javax.swing.JLabel newPassLbl;
    private javax.swing.JTextField newPassTf;
    private javax.swing.JPanel passwordPanel;
    private javax.swing.JButton sendBtn;
    private javax.swing.JButton verifyBtn;
    // End of variables declaration//GEN-END:variables
}
