/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shoemanagementsystem;

import com.mysql.cj.protocol.Resultset;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.font.TextAttribute;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author mnawa
 */
public class LoginPage extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement st = null;
    ResultSet rs = null;

    int xMouse;
    int yMouse;

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        Image a = Toolkit.getDefaultToolkit().getImage("E:\\ShoeManagementSystem\\src\\Images\\SSMS-200.jpg");
        setIconImage(a);
        capsLock.setVisible(false);

        Font font = forgetpassLbl.getFont();
        Map attrib = font.getAttributes();
        attrib.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        forgetpassLbl.setFont(font.deriveFont(attrib));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        usernameFld = new javax.swing.JTextField();
        passwordFld = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        closeLbl = new javax.swing.JLabel();
        forgetpassLbl = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        visibleBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        capsLock = new javax.swing.JLabel();
        minimizeLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(29, 29, 29));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameFld.setBackground(new java.awt.Color(31, 31, 31));
        usernameFld.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        usernameFld.setForeground(new java.awt.Color(255, 255, 255));
        usernameFld.setText("username");
        usernameFld.setBorder(null);
        usernameFld.setCaretColor(new java.awt.Color(255, 255, 255));
        usernameFld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameFldMouseClicked(evt);
            }
        });
        usernameFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFldActionPerformed(evt);
            }
        });
        usernameFld.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFldFocusGained(evt);
            }
        });
        usernameFld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameFldKeyPressed(evt);
            }
        });
        jPanel1.add(usernameFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 83, 176, 34));

        passwordFld.setBackground(new java.awt.Color(31, 31, 31));
        passwordFld.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passwordFld.setForeground(new java.awt.Color(255, 255, 255));
        passwordFld.setText("password");
        passwordFld.setBorder(null);
        passwordFld.setCaretColor(new java.awt.Color(255, 255, 255));
        passwordFld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordFldMouseClicked(evt);
            }
        });
        passwordFld.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFldFocusGained(evt);
            }
        });
        passwordFld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordFldKeyPressed(evt);
            }
        });
        jPanel1.add(passwordFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 142, 176, 34));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 123, 176, 8));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 181, 176, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_user_30px.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 83, -1, 34));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_lock_30px_1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 150, -1, -1));

        closeLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        closeLbl.setForeground(new java.awt.Color(255, 255, 255));
        closeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_close_window_18px.png"))); // NOI18N
        closeLbl.setToolTipText("Close");
        closeLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeLblMouseExited(evt);
            }
        });
        jPanel1.add(closeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 27, 31));

        forgetpassLbl.setBackground(new java.awt.Color(255, 153, 51));
        forgetpassLbl.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        forgetpassLbl.setForeground(new java.awt.Color(199, 199, 199));
        forgetpassLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forgetpassLbl.setText("forget pass?");
        forgetpassLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgetpassLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                forgetpassLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                forgetpassLblMouseExited(evt);
            }
        });
        jPanel1.add(forgetpassLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 80, 20));

        loginBtn.setBackground(new java.awt.Color(187, 134, 252));
        loginBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        loginBtn.setText("Login");
        loginBtn.setToolTipText("login(Press Enter)");
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        loginBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginBtnKeyPressed(evt);
            }
        });
        jPanel1.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 273, 176, 34));

        visibleBtn.setBackground(new java.awt.Color(31, 31, 31));
        visibleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_eye_20px.png"))); // NOI18N
        visibleBtn.setToolTipText("show/hide password");
        visibleBtn.setBorder(null);
        visibleBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visibleBtnMouseClicked(evt);
            }
        });
        visibleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visibleBtnActionPerformed(evt);
            }
        });
        jPanel1.add(visibleBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 20, 20));

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SMSS-2000000.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 116, 164, 130));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 73, -1, 234));

        capsLock.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        capsLock.setForeground(new java.awt.Color(255, 255, 255));
        capsLock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        capsLock.setText("CAPS lock is on");
        jPanel1.add(capsLock, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, 20));

        minimizeLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        minimizeLbl.setForeground(new java.awt.Color(255, 255, 255));
        minimizeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizeLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_minimize_window_18px.png"))); // NOI18N
        minimizeLbl.setToolTipText("Minimize");
        minimizeLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeLblMouseExited(evt);
            }
        });
        jPanel1.add(minimizeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 27, 31));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 390));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFldActionPerformed

    private void closeLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLblMouseClicked
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_closeLblMouseClicked
    int id;
    private void forgetpassLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetpassLblMouseClicked
        // TODO add your handling code here:
        getData();
        this.dispose();
        forgetPass f = new forgetPass();
        f.setVisible(true);
        f.getEmail(id);
    }//GEN-LAST:event_forgetpassLblMouseClicked

    private void forgetpassLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetpassLblMouseEntered

        forgetpassLbl.setForeground(Color.white);
        Font font = forgetpassLbl.getFont();
        Map attrib = font.getAttributes();
        attrib.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        forgetpassLbl.setFont(font.deriveFont(attrib));

    }//GEN-LAST:event_forgetpassLblMouseEntered

    private void forgetpassLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetpassLblMouseExited
        forgetpassLbl.setForeground(new Color(199, 199, 199));

        Font font = forgetpassLbl.getFont();
        Map attrib = font.getAttributes();
        attrib.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        forgetpassLbl.setFont(font.deriveFont(attrib));

    }//GEN-LAST:event_forgetpassLblMouseExited

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed

        login();
    }//GEN-LAST:event_loginBtnActionPerformed
    ImageIcon image1 = new ImageIcon("E:\\ShoeManagementSystem\\src\\Images\\icons8_eye_20px.png");
    ImageIcon image2 = new ImageIcon("E:\\ShoeManagementSystem\\src\\Images\\icons8_invisible_20px_1.png");

    int counter = 1;
    private void visibleBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visibleBtnMouseClicked
        // TODO add your handling code here:
        if (counter == 1) {
            passwordFld.setEchoChar((char) 0);
            visibleBtn.setIcon(image2);
            counter--;
        } else {
            passwordFld.setEchoChar('\u25cf');
            visibleBtn.setIcon(image1);
            counter = 1;
        }


    }//GEN-LAST:event_visibleBtnMouseClicked
    private void visibleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visibleBtnActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_visibleBtnActionPerformed

    private void usernameFldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameFldMouseClicked

        if (usernameFld.getText().equals("username")) {
            usernameFld.setText("");
        }


    }//GEN-LAST:event_usernameFldMouseClicked

    private void passwordFldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordFldMouseClicked
        // TODO add your handling code here:

        if (String.valueOf(passwordFld.getPassword()).equals("password")) {
            passwordFld.setText("");
        }
    }//GEN-LAST:event_passwordFldMouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void closeLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLblMouseEntered
        // TODO add your handling code here:
        closeLbl.setBackground(Color.red);
    }//GEN-LAST:event_closeLblMouseEntered

    private void closeLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLblMouseExited
        // TODO add your handling code here:
        closeLbl.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_closeLblMouseExited

    private void loginBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginBtnKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            login();
        }
    }//GEN-LAST:event_loginBtnKeyPressed

    private void usernameFldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameFldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            passwordFld.grabFocus();
        }
        if (usernameFld.getText().equals("username")) {

            usernameFld.setText("");

        }
    }//GEN-LAST:event_usernameFldKeyPressed

    private void passwordFldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            login();
        }

        if (String.valueOf(passwordFld.getPassword()).equals("password")) {
            passwordFld.setText("");
        }

        // it will check if CAPS lock is on or off
        if (Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK) == true) {
            capsLock.setVisible(true);

        } else {
            capsLock.setVisible(false);

        }
    }//GEN-LAST:event_passwordFldKeyPressed

    private void passwordFldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFldFocusGained
        if (String.valueOf(passwordFld.getPassword()).equals("password")) {
            passwordFld.setText("");
        }
        // it will check if CAPS lock is on or off

        if (Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK) == true) {
            capsLock.setVisible(true);

        } else {
            capsLock.setVisible(false);

        }


    }//GEN-LAST:event_passwordFldFocusGained

    private void usernameFldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFldFocusGained
        if (usernameFld.getText().equals("username")) {

            usernameFld.setText("");

        }
    }//GEN-LAST:event_usernameFldFocusGained

    private void minimizeLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLblMouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeLblMouseClicked

    private void minimizeLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLblMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_minimizeLblMouseEntered

    private void minimizeLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLblMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_minimizeLblMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Darcula".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel capsLock;
    private javax.swing.JLabel closeLbl;
    private javax.swing.JLabel forgetpassLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel minimizeLbl;
    private javax.swing.JPasswordField passwordFld;
    private javax.swing.JTextField usernameFld;
    private javax.swing.JButton visibleBtn;
    // End of variables declaration//GEN-END:variables

    // this method is to get id from signup table and then get the email address of that id and set this in forget pass module
    void getData() {
        try {
            conn = DBConnection.getConnection();
            st = conn.prepareStatement("select id from owner_signup where o_username=?");
            st.setString(1, usernameFld.getText());

            rs = st.executeQuery();

            if (rs.next()) {
                id = rs.getInt("id");
            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void login() {
        if (usernameFld.getText().isEmpty() || String.valueOf(passwordFld.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(this, "username/password can't be empty", "empty fields", JOptionPane.ERROR_MESSAGE);
        } else if (usernameFld.getText().equals("username") || String.valueOf(passwordFld.getPassword()).equals("password")) {
            JOptionPane.showMessageDialog(this, "First enter valid username & password", "Invalid data", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                conn = DBConnection.getConnection();
                st = conn.prepareStatement("select id,o_name from owner_signup where o_username=? AND o_password=?");
                st.setString(1, usernameFld.getText().trim());
                st.setString(2, String.valueOf(passwordFld.getPassword()));
                rs = st.executeQuery();

                if (rs.next()) {

                    id = rs.getInt("id");
                    String name = rs.getString("o_name");
                    JOptionPane.showMessageDialog(this, "Valid cradentials...");

                    String sql = "insert into owner_login(o_id,login_time,login_date) values(" + id + ",curtime(),curdate())";
                    st = conn.prepareStatement(sql);
                    st.execute();

                    userdetails.userId(id);
                    userdetails.username(name.toUpperCase());

                    this.dispose();
                    MainMenuFrame menu = new MainMenuFrame();
                    menu.setVisible(true);

                    MainMenuFrame.setUsername();

                } else {
                    JOptionPane.showMessageDialog(this, "Invalid cradentials, TRY AGAIN...");

                }
            } catch (SQLException ex) {
                Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}
