/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shoemanagementsystem;

import java.awt.Font;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Timer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author mnawa
 */
public class MainMenuFrame extends javax.swing.JFrame {

    Connection conn = null;
    Statement st = null;
    ResultSet rs = null;

    int xMouse;
    int yMouse;

    Font enterFont = new Font("Segoe UI", Font.BOLD, 14);
    Font exitFont = new Font("Segoe UI", Font.PLAIN, 14);

    // defining icons
    ImageIcon dashboardWhite = new ImageIcon("E:\\ShoeManagementSystem\\src\\demeImages\\icons8_dashboard_80px_1.png");
    ImageIcon dashboardPurple = new ImageIcon("E:\\ShoeManagementSystem\\src\\demeImages\\icons8_dashboard_80px.png");

    ImageIcon salePurple = new ImageIcon("E:\\ShoeManagementSystem\\src\\demeImages\\icons8_sell_stock_80px.png");
    ImageIcon saleWhite = new ImageIcon("E:\\ShoeManagementSystem\\src\\demeImages\\icons8_sell_stock_80px_1.png");

    ImageIcon purchaseWhite = new ImageIcon("E:\\ShoeManagementSystem\\src\\demeImages\\icons8_card_payment_80px_1.png");
    ImageIcon purchasePurple = new ImageIcon("E:\\ShoeManagementSystem\\src\\demeImages\\icons8_card_payment_80px.png");

    ImageIcon empPurple = new ImageIcon("E:\\ShoeManagementSystem\\src\\demeImages\\icons8_management_80px.png");
    ImageIcon empWhite = new ImageIcon("E:\\ShoeManagementSystem\\src\\demeImages\\icons8_management_80px_1.png");

    ImageIcon stockWhite = new ImageIcon("E:\\ShoeManagementSystem\\src\\demeImages\\icons8_warehouse_80px_1.png");
    ImageIcon stockPurple = new ImageIcon("E:\\ShoeManagementSystem\\src\\demeImages\\icons8_warehouse_80px.png");

    ImageIcon dealerWhite = new ImageIcon("E:\\ShoeManagementSystem\\src\\demeImages\\icons8_supplier_80px_1.png");
    ImageIcon dealerPurple = new ImageIcon("E:\\ShoeManagementSystem\\src\\demeImages\\icons8_supplier_80px.png");

    ImageIcon reportPurple = new ImageIcon("E:\\ShoeManagementSystem\\src\\demeImages\\icons8_account_80px.png");
    ImageIcon reportWhite = new ImageIcon("E:\\ShoeManagementSystem\\src\\demeImages\\icons8_account_80px_1.png");

    ImageIcon settingsWhite = new ImageIcon("E:\\ShoeManagementSystem\\src\\demeImages\\icons8_gears_80px_1.png");
    ImageIcon settingspuple = new ImageIcon("E:\\ShoeManagementSystem\\src\\demeImages\\icons8_gears_80px.png");

    public MainMenuFrame() {
        initComponents();
        showDateTime();

    }

    void showDateTime() {
        SimpleDateFormat timeformat = new SimpleDateFormat("hh:mm a");
        SimpleDateFormat dateformat = new SimpleDateFormat("dd/MM/yyyy");
        Date time = new Date();
        timeLbl.setText(timeformat.format(time));
        dateLbl.setText(dateformat.format(time));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tittlePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        loggedinUserLbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        MenuPanel = new javax.swing.JPanel();
        Dashboard = new javax.swing.JLabel();
        Sales = new javax.swing.JLabel();
        Purchase = new javax.swing.JLabel();
        Employee = new javax.swing.JLabel();
        Stock = new javax.swing.JLabel();
        Dealer = new javax.swing.JLabel();
        Report = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        timeLbl = new javax.swing.JLabel();
        dateLbl = new javax.swing.JLabel();
        Setting = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tittlePanel.setBackground(new java.awt.Color(10, 10, 10));
        tittlePanel.setForeground(new java.awt.Color(187, 134, 252));
        tittlePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("you are logged in as ");
        tittlePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 12, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ADMIN");
        tittlePanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 11, -1, -1));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("logout");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        tittlePanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, -1, -1));

        loggedinUserLbl.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        loggedinUserLbl.setForeground(new java.awt.Color(255, 255, 255));
        loggedinUserLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demeImages/icons8_user_50px_1.png"))); // NOI18N
        loggedinUserLbl.setText("Welcome ABDUL REHMAN");
        loggedinUserLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loggedinUserLbl.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tittlePanel.add(loggedinUserLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 11, 150, 65));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(97, 188, 71));
        jLabel5.setText("SHOE");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tittlePanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 110, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(37, 183, 234));
        jLabel8.setText("HUB");
        tittlePanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, 30));

        getContentPane().add(tittlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 90));

        MenuPanel.setBackground(new java.awt.Color(18, 18, 18));

        Dashboard.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Dashboard.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demeImages/icons8_dashboard_80px_1.png"))); // NOI18N
        Dashboard.setText("Dashboard");
        Dashboard.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Dashboard.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DashboardMouseExited(evt);
            }
        });

        Sales.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Sales.setForeground(new java.awt.Color(255, 255, 255));
        Sales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demeImages/icons8_sell_stock_80px_1.png"))); // NOI18N
        Sales.setText("Sales");
        Sales.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Sales.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Sales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalesMouseExited(evt);
            }
        });

        Purchase.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Purchase.setForeground(new java.awt.Color(255, 255, 255));
        Purchase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demeImages/icons8_card_payment_80px_1.png"))); // NOI18N
        Purchase.setText("Purchase");
        Purchase.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Purchase.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Purchase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PurchaseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PurchaseMouseExited(evt);
            }
        });

        Employee.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Employee.setForeground(new java.awt.Color(255, 255, 255));
        Employee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demeImages/icons8_management_80px_1.png"))); // NOI18N
        Employee.setText("Employee");
        Employee.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Employee.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Employee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmployeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EmployeeMouseExited(evt);
            }
        });

        Stock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Stock.setForeground(new java.awt.Color(255, 255, 255));
        Stock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demeImages/icons8_warehouse_80px_1.png"))); // NOI18N
        Stock.setText("Stock");
        Stock.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Stock.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Stock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StockMouseExited(evt);
            }
        });

        Dealer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Dealer.setForeground(new java.awt.Color(255, 255, 255));
        Dealer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demeImages/icons8_supplier_80px_1.png"))); // NOI18N
        Dealer.setText("Dealer");
        Dealer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Dealer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Dealer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DealerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DealerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DealerMouseExited(evt);
            }
        });

        Report.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Report.setForeground(new java.awt.Color(255, 255, 255));
        Report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demeImages/icons8_account_80px_1.png"))); // NOI18N
        Report.setText("Reports");
        Report.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Report.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReportMouseExited(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(10, 10, 10));

        timeLbl.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        timeLbl.setForeground(new java.awt.Color(255, 255, 255));
        timeLbl.setText("12:51:12 PM");

        dateLbl.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        dateLbl.setForeground(new java.awt.Color(255, 255, 255));
        dateLbl.setText("12:51:12 PM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateLbl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(timeLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );

        Setting.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Setting.setForeground(new java.awt.Color(255, 255, 255));
        Setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demeImages/icons8_gears_80px_1.png"))); // NOI18N
        Setting.setText("Settings");
        Setting.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Setting.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SettingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SettingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SettingMouseExited(evt);
            }
        });

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Report)
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Employee)
                            .addComponent(Dashboard))
                        .addGap(150, 150, 150)
                        .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Sales)
                            .addComponent(Stock))))
                .addGap(153, 153, 153)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Purchase)
                    .addComponent(Dealer)
                    .addComponent(Setting))
                .addContainerGap(86, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Purchase)
                    .addComponent(Sales)
                    .addComponent(Dashboard))
                .addGap(18, 18, 18)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Employee)
                    .addComponent(Stock)
                    .addComponent(Dealer))
                .addGap(18, 18, 18)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Report)
                    .addComponent(Setting))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(MenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 720, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked

        logout();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();

    }//GEN-LAST:event_formMousePressed

    private void DashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMouseEntered
        Dashboard.setIcon(dashboardPurple);
        Dashboard.setFont(enterFont);
    }//GEN-LAST:event_DashboardMouseEntered

    private void DashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMouseExited
        Dashboard.setIcon(dashboardWhite);
        Dashboard.setFont(exitFont);

    }//GEN-LAST:event_DashboardMouseExited

    private void SalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalesMouseEntered
        Sales.setIcon(salePurple);
        Sales.setFont(enterFont);
    }//GEN-LAST:event_SalesMouseEntered

    private void SalesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalesMouseExited
        Sales.setIcon(saleWhite);
        Sales.setFont(exitFont);
    }//GEN-LAST:event_SalesMouseExited

    private void PurchaseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PurchaseMouseEntered
        Purchase.setIcon(purchasePurple);
        Purchase.setFont(enterFont);
    }//GEN-LAST:event_PurchaseMouseEntered

    private void PurchaseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PurchaseMouseExited
        Purchase.setIcon(purchaseWhite);
        Purchase.setFont(exitFont);
    }//GEN-LAST:event_PurchaseMouseExited

    private void EmployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeMouseEntered
        Employee.setIcon(empPurple);
        Employee.setFont(enterFont);
    }//GEN-LAST:event_EmployeeMouseEntered

    private void EmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeMouseExited
        Employee.setIcon(empWhite);
        Employee.setFont(exitFont);
    }//GEN-LAST:event_EmployeeMouseExited

    private void StockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockMouseEntered
        Stock.setIcon(stockPurple);
        Stock.setFont(enterFont);
    }//GEN-LAST:event_StockMouseEntered

    private void StockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockMouseExited
        Stock.setIcon(stockWhite);
        Stock.setFont(exitFont);
    }//GEN-LAST:event_StockMouseExited

    private void DealerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DealerMouseEntered
        Dealer.setIcon(dealerPurple);
        Dealer.setFont(enterFont);
    }//GEN-LAST:event_DealerMouseEntered

    private void DealerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DealerMouseExited
        Dealer.setIcon(dealerWhite);
        Dealer.setFont(exitFont);
    }//GEN-LAST:event_DealerMouseExited

    private void ReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportMouseEntered
        Report.setIcon(reportPurple);
        Report.setFont(enterFont);
    }//GEN-LAST:event_ReportMouseEntered

    private void ReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportMouseExited
        Report.setIcon(reportWhite);
        Report.setFont(exitFont);
    }//GEN-LAST:event_ReportMouseExited

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        logout();
    }//GEN-LAST:event_formWindowClosing

    private void EmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeMouseClicked
        this.setVisible(false);
        new EmployeeForm().setVisible(true);
        getusername();
    }//GEN-LAST:event_EmployeeMouseClicked

    private void DealerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DealerMouseClicked
        this.dispose();
        new DealerForm().setVisible(true);
        getusername();
    }//GEN-LAST:event_DealerMouseClicked

    private void SettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingMouseEntered
        Setting.setIcon(settingspuple);
    }//GEN-LAST:event_SettingMouseEntered

    private void SettingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingMouseExited
        Setting.setIcon(settingsWhite);
    }//GEN-LAST:event_SettingMouseExited

    private void SettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingMouseClicked
        this.dispose();
       Settings st= new Settings();
       st.setVisible(true);
      
        getusername();
    }//GEN-LAST:event_SettingMouseClicked

    // this method is called inside EmployeeForm class to again set the username to the logged in user
    static void setnameAfterHide(String name) {
        loggedinUserLbl.setText("Welcome " + name);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Darcula".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
//       String theme= Settings.getFeelAndLook();
            
              
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuFrame().setVisible(true);
            }
        });

    }
    static String user;

    static String user1;

    /// this method is used to store logged in username because when after returning to home page username 
    //  is changed as a result of new Instance of MainMenuFrame class  
    void getusername() {
        user1 = user;
       
    }

    // this method is called when user press the login button on LoginPage class it will set the username to the user who is 
    // currently logged in 
    static void setusername(String name) {
        user = name;
        loggedinUserLbl.setText("Welcome " + user);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dashboard;
    private javax.swing.JLabel Dealer;
    private javax.swing.JLabel Employee;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JLabel Purchase;
    private javax.swing.JLabel Report;
    private javax.swing.JLabel Sales;
    private javax.swing.JLabel Setting;
    private javax.swing.JLabel Stock;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JLabel loggedinUserLbl;
    private javax.swing.JLabel timeLbl;
    private javax.swing.JPanel tittlePanel;
    // End of variables declaration//GEN-END:variables

    Time time;

    public void logout() {
        try {
            int id = 0;

            if (JOptionPane.showConfirmDialog(this, "Are you sure?", "Confirm", JOptionPane.YES_NO_CANCEL_OPTION) == 0) {
                conn = DBConnection.getConnection();
                st = conn.createStatement();
                rs = st.executeQuery("select max(id),curtime() from owner_login"); // query for geting logout time

                if (rs.next()) {
                    id = rs.getInt(1);
                    time = rs.getTime(2);
                }

                st.executeUpdate("update owner_login set logout_time='" + time + "' where id=" + id);
                this.dispose();
                new LoginPage().setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainMenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

}
